# Generated by Django 4.2.7 on 2026-04-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, help_text='Product specifications, one per line'),
        ),
    ]
